# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .app_deploy import *
from .app_image import *
from .app_image_deploy import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "container-services",
  "mod": "index",
  "fqn": "pulumi_container_services",
  "classes": {
   "container-services:index:AppDeploy": "AppDeploy",
   "container-services:index:AppImage": "AppImage",
   "container-services:index:AppImageDeploy": "AppImageDeploy"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "container-services",
  "token": "pulumi:providers:container-services",
  "fqn": "pulumi_container_services",
  "class": "Provider"
 }
]
"""
)
