// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AppDeploy extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'container-services:index:AppDeploy';

    /**
     * Returns true if the given object is an instance of AppDeploy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppDeploy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppDeploy.__pulumiType;
    }

    public /*out*/ readonly loadbalancerDnsName!: pulumi.Output<string>;

    /**
     * Create a AppDeploy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppDeployArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.imageReference === undefined) && !opts.urn) {
                throw new Error("Missing required property 'imageReference'");
            }
            resourceInputs["accessCidr"] = args ? args.accessCidr : undefined;
            resourceInputs["cpu"] = args ? args.cpu : undefined;
            resourceInputs["imageReference"] = args ? args.imageReference : undefined;
            resourceInputs["memory"] = args ? args.memory : undefined;
            resourceInputs["loadbalancerDnsName"] = undefined /*out*/;
        } else {
            resourceInputs["loadbalancerDnsName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppDeploy.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AppDeploy resource.
 */
export interface AppDeployArgs {
    accessCidr?: string;
    cpu?: number;
    imageReference: pulumi.Input<string>;
    memory?: number;
}
