// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AppImage extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'container-services:index:AppImage';

    /**
     * Returns true if the given object is an instance of AppImage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppImage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppImage.__pulumiType;
    }

    public /*out*/ readonly imageRef!: pulumi.Output<string>;
    public /*out*/ readonly repositoryPath!: pulumi.Output<string>;

    /**
     * Create a AppImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppImageArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.dockerFilePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dockerFilePath'");
            }
            resourceInputs["destination"] = args ? args.destination : undefined;
            resourceInputs["dockerFilePath"] = args ? args.dockerFilePath : undefined;
            resourceInputs["imageRef"] = undefined /*out*/;
            resourceInputs["repositoryPath"] = undefined /*out*/;
        } else {
            resourceInputs["imageRef"] = undefined /*out*/;
            resourceInputs["repositoryPath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppImage.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a AppImage resource.
 */
export interface AppImageArgs {
    destination?: string;
    dockerFilePath: string;
}
