// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AppDeployArgs } from "./appDeploy";
export type AppDeploy = import("./appDeploy").AppDeploy;
export const AppDeploy: typeof import("./appDeploy").AppDeploy = null as any;
utilities.lazyLoad(exports, ["AppDeploy"], () => require("./appDeploy"));

export { AppImageArgs } from "./appImage";
export type AppImage = import("./appImage").AppImage;
export const AppImage: typeof import("./appImage").AppImage = null as any;
utilities.lazyLoad(exports, ["AppImage"], () => require("./appImage"));

export { AppImageDeployArgs } from "./appImageDeploy";
export type AppImageDeploy = import("./appImageDeploy").AppImageDeploy;
export const AppImageDeploy: typeof import("./appImageDeploy").AppImageDeploy = null as any;
utilities.lazyLoad(exports, ["AppImageDeploy"], () => require("./appImageDeploy"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "container-services:index:AppDeploy":
                return new AppDeploy(name, <any>undefined, { urn })
            case "container-services:index:AppImage":
                return new AppImage(name, <any>undefined, { urn })
            case "container-services:index:AppImageDeploy":
                return new AppImageDeploy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("container-services", "index", _module)
pulumi.runtime.registerResourcePackage("container-services", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:container-services") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
